### ISSUE TITLE
Add more content: user reviews, useful resources about projects

### ISSUE THREAD

**Issue by michaelrambeau** [michaelrambeau/bestofjs-webui#2]
Now bestof.js.org application only displays the number of stars from Github.
It would be interesting to be able to see more qualitative content such as:

* User reviews (to see which projects developers really appreciate and recommend)
* Interesting resources such as blog entries, tutorials that explain how to use the project in real applications...

Content will be generated by users logged with Github.

Questions:

* Where to store the new content ? Use a backend as a service like [parse.com](https://parse.com/) or [firebase](https://www.firebase.com/) and take advantage of user authentication that is available out-of-the-box ?
* Since the content can be generated by anyone (after logging with Github), do we need content moderation to avoid spam and other irrelevant content ?
* Reviews and Resources will be loaded when a project page is opened (`/projects/:id`). How to update project lists displayed in the homepage and in the "tag" pages ? (/tags/:code)

## User reviews

A user review could be made of 2 parts: a user score (from 1 to 5) and a comment (markdown content)

User score meaning:

* 5: Highly recommended over any other choice, a great piece of software
* 4: a recommended choice
* 3: it does the job, nothing more, nothing less
* 2: some annoying defects
* 1: really bad

## Useful links

A "useful resource" would be made of a URL (link to the blog entry), a title and a comment (optional) that describes the content of the link.
Reading the latest issues of javascriptweekly.com will be useful to get initial data.

**Comment by ragamufin** [comment]
Makes sense. 1 - 5 is good, I think Google Play and the App Store does it that way right?

Ideally they should be stored in the cloud however since all of this revolves around github, is there a way to use github to store these? That way other projects could consume the data as well. Thinking about it that way it could be done somehow using github pages or by using the issue system of github? Is it possible to add a label like "Review" to a repo and require users to put their comments in a specified format/markdown with the rating and/or the text review so that it can be parsed out?

**Comment by michaelrambeau** [comment]
Thank you for your comments @ragamufin.
Yes, I think users are familiars with the 1 to 5 scale because of reviews seen on app stores and on sites like Amazon.

#### Screenshot from GooglePlay:

![image](https://cloud.githubusercontent.com/assets/5546996/10894461/1cb807aa-81f2-11e5-9577-91ffba4dd278.png)

![image](https://cloud.githubusercontent.com/assets/5546996/10894498/4afd3ee6-81f2-11e5-8adb-a80a36b39124.png)



#### Screenshot from Amazon:

In the product list:

![image](https://cloud.githubusercontent.com/assets/5546996/10894364/78db502e-81f1-11e5-8c51-172e5a1f102c.png)

In the product page:

![image](https://cloud.githubusercontent.com/assets/5546996/10894233/c5168ce8-81f0-11e5-911c-496cc3268d83.png)

#### Screenshot from Apple store

![image](https://cloud.githubusercontent.com/assets/5546996/10894781/e3a4e85a-81f3-11e5-830e-82dc633b83c5.png)


#### About stars

The problem is I cannot use "stars" for reviews because I already use the concept of Github stars (`stargazers_count`) in the application, it would be confusing I think... So I may need an other shape.
So I think about the heart shape (a bit like the "health bar" in Zelda video game)...

Note: semantic-ui library has a [rating](http://semantic-ui.com/modules/rating.html) module, with both "star" and "heart" shapes available:

![image](https://cloud.githubusercontent.com/assets/5546996/10894618/1e67c86e-81f3-11e5-83b6-4aa29dde3e64.png)

So I think using hearts makes sense.

**Comment by ragamufin** [comment]
Hearts make sense to me and like you said, it avoids confusion with github stars. 

What did you think about the idea to use github issues (renaming one of the labels to "reviews") or pages somehow to store the ratings, that way it can still be in the github ecosystem? Or other ideas?

**Comment by michaelrambeau** [comment]
I have never thought about using Github issues as a storage system, that is an interesting idea.
Every project used in bestof.js.prg could be stored be as a single "issue".
And every comment posted would be a new comment on the issue.

The pros:
* Easy to check all the comments related to a project, it would create a consistent thread.
* free, no size limit, 
* integration with Github of course (login from Github)

The cons:
* Comments are basically a single field using markdown, I would need a system to code/decode the user rating somehow
* ACL problem ? Users would not be allowed to create / update reviews directly from the usual Github UI, there would be a process that generates the comments in the issues, from the rating and the review entered by the user. But I don't think it is possible to update Github comment policy (everyone can update his own comment at any time).

**Comment by ragamufin** [comment]
It's one idea. If it's too cumbersome then I think you shouldn't bother with it but do whatever is simplest yet effective. For the second con, I was thinking not that you would post in your own account but that the review would come from the user's account, so you'd have to allow for them to sign in via the github api before they place their review and then their review would go into the issues list. Since it would be in their account, they could edit the review at any time, even through github itself.

**Comment by michaelrambeau** [comment]
Working on a solution using 2 external services:
* http://parse.com/ to manage user generated content
* https://auth0.com/ to manage user authentication using Github account

### Basic tests

With parse.com, it was pretty easy to create a REST API to fetch, create and update user reviews.

With auth0.com, I implemented the "Sign in with Github" feature.
By including a single JS file from a CDN, a `lock` object is available, that provides a method to sign in:

```
lock.show(function onLogin(err, profile, token) {
});
```

A login form is displayed in a modal when pushing the "Sign in" button.

The callback returns the user Github profile and the security token (a 262 character String)

User profile:

```
{
  "name": "Michael Rambeau",
  "picture": "https://avatars.githubusercontent.com/u/5546996?v=3",
  "nickname": "michaelrambeau",
  "gravatar_id": "",
  "url": "https://api.github.com/users/michaelrambeau",
  "html_url": "https://github.com/michaelrambeau",
  "followers_url": "https://api.github.com/users/michaelrambeau/followers",
  "following_url": "https://api.github.com/users/michaelrambeau/following{/other_user}",
  "gists_url": "https://api.github.com/users/michaelrambeau/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/michaelrambeau/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/michaelrambeau/subscriptions",
  "organizations_url": "https://api.github.com/users/michaelrambeau/orgs",
  "repos_url": "https://api.github.com/users/michaelrambeau/repos",
  "events_url": "https://api.github.com/users/michaelrambeau/events{/privacy}",
  "received_events_url": "https://api.github.com/users/michaelrambeau/received_events",
  "type": "User",
  "site_admin": false,
  "blog": "http://michaelrambeau.com",
  "location": "Osaka, Japan",
  "public_repos": 15,
  "public_gists": 3,
  "followers": 5,
  "following": 7,
  "updated_at": "2016-01-02T23:34:34.572Z",
  "clientID": "MJjUkmsoTaPHvp7sQOUjyFYOm2iI3chx",
  "user_id": "github|5546996",
  "identities": [
    {
      "access_token": "5b7d140b21097fc6019b081ff9772eb45d341245",
      "provider": "github",
      "user_id": 5546996,
      "connection": "github",
      "isSocial": true
    }
  ],
  "created_at": "2016-01-02T08:36:09.378Z",
  "global_client_id": "ScCv5gshJ2Vf5III5ATyPbjjnyXWbJDz"
}
```

The token can be stored locally using `localStorage`.
And then, when the user reloads the page, the token is read from local storage and the application gets the user profile by calling `lock.getProfile(token, cb)`

### Access control

So far, there is no access control, anyone can create / update reviews, passing any username.
Next step: implement access control, connecting somehow authentication and security rules about data stored in parse.com.

Rules:
* Reviews can only be created by authenticated users.
* Only one review by user and by project
* Users can only update reviews they created

Can it be done without implementing server-side code (without implementing any new micro-service ?)

**Comment by michaelrambeau** [comment]
A "pre-release" version is available on https://bestofjs.firebaseapp.com

![image](https://cloud.githubusercontent.com/assets/5546996/14236865/d18e5d00-fa56-11e5-8163-a74495b3797a.png)

TO DO before the production release:

* Limit text and textarea field length (in both API and UI) for user generated content.
* Add a view for admins somewhere, to be able to check newly created reviews and links (using a boolean flag "moderated" ?)

```
moderation:{
  checked: true,
  valid: true,
  checkedBy: <username>,
  checkedAt: <date>
}
```

**Comment by michaelrambeau** [comment]
The "user generated content" feature has been released, it is kind of "beta" version because the current implementation cannot scale well: all "reviews" and "links" are loaded once, when the application starts, there is no pagination. No "moderation" feature either.
