### ISSUE TITLE
Add npm modules data

### ISSUE THREAD

**Issue by michaelrambeau** [michaelrambeau/bestofjs-webui#20]
It could be nice to include data from npm modules in the application:
- npm module name
- version 
- dependencies

npm module name could be used as a key for projects URLs (now Github repository name is used, see isuee #19)

**Comment by michaelrambeau** [comment]
For most of the projects, we can find npm module name from Github package.json file.

Special cases:

* Some projects do not exist in npm (documentation projects like `devdocs.io` for example, but also Meteor)
* Some projects are multipackages, like Babel
* Some projects use "npm scoped packages", Cycle.js for example. Package name: `@cycle/core` http://registry.npmjs.org/core/latest?scope=@cycle

Implementation plan:

STEP 1: write a batch that initializes npm module name by reading package.json, from Github default branch

STEP 2: update the daily batch to fetch data from npm registry. Example of npm API request: http://registry.npmjs.org/redux/latest

**Comment by michaelrambeau** [comment]
Fixing npm module names

Multi-packages repos

* poucbdb => `pouchdb-core`
* babel => `babel-core` (I could choose `babel-cli` but it seems that babel-core is more popular, 9 M downloads last month!)

Projects without package.json

* horizon => `horizon`
* uWebSockets => `uws`
* `react-starter-kit`

Package.json without name property

* `cssx`
* `muicss`
* `nativescript`
* jest => `jest-cli`

Fixing package.json name

* mern-starter => `mern-cli`
* mjml: `mjml-repo` => `mjml`
* graph: graphql-spec => `graphql-relay`
* recompose-build => `recompose`
* material-ui-build => `material-ui`
* angular-material-source => `angular-material`
* fluxible-repo => `fluxible`
* pencilblue => `pencilblue-cli`
* babylon.js => `babylonjs`

**Comment by michaelrambeau** [comment]
Closing the issue for now, we aggregate data from npm, packagequality.com and npms.io.

To do: make the process automatic. Now I have to manually run the command `node batches npm` from bestofjs-batches repository, in order to update the section related to npm (see screenshot)

![image](https://cloud.githubusercontent.com/assets/5546996/20855702/af8eae7e-b943-11e6-8fcd-58e7caa823f3.png)

**Comment by abumalick** [comment]
I don't see npm data anymore. Did you remove it ?

**Comment by michaelrambeau** [comment]
Hello @abumalick 
The package version number is still displayed and I've added data about the bundle size, the size of the package on the disk and the licenses but there is no more data about the Npms.io and PackageQuality.com "scores".

What do you think, you'd like to see again the 2 scores?
Thank you for your feedback!

![image](https://user-images.githubusercontent.com/5546996/48804937-52185a00-ed59-11e8-8b19-4b8ddf7941da.png)

**Comment by abumalick** [comment]
actually I feel that the best metric in npm is the number of download by week or month. I think that it is even a better metric than GitHub stars for most packages.

An example:
React and Vuejs.
Vuejs have more stars on github and we coule think that it is more used than React.

When you look at npm weekly downloads:
Vue: 651600
React: 3722500

Which is a *huge* difference !

It matches a bit better the stats in stateofjs from this year:
React at 16k users and vue at 8k...

I eould really love to have this metric when available and be able to order according to it..

Thanks for the great resource by the way ! Your site is really interesting

**Comment by michaelrambeau** [comment]
Thank you for your interesting comments.
It makes senses, I will think about how to integrate the download numbers from NPM.
About the difference that you consider "huge": a lot of developers in China download `Vue.js` from other registries than NPM. 
And I guess a lot of people still simply download Vue.js from a CDN in their web pages with a `<script>` tag since it's pretty easy to do simple things with Vue.js without any building process.

**Comment by abumalick** [comment]
Makes senses.

Thanks for your insight!
