### ISSUE TITLE
Greenshock --> Greensock

### ISSUE THREAD

**Issue by crazy4groovy** [michaelrambeau/bestofjs-webui#24]
Typo (no "h")

http://bestof.js.org/projects/greenshock

**Comment by michaelrambeau** [comment]
Hello @crazy4groovy , thank you.
I have just fixed the typo (disable the browser cache if the typo is still displayed on your screen).
If you have any feedback about bestof.js.org, or if there is any feature that could be useful for you, do not hesitate to contact me!

![image](https://cloud.githubusercontent.com/assets/5546996/17639476/9eefa5aa-612d-11e6-88db-15a3e761d6e0.png)

**Comment by crazy4groovy** [comment]
Thanks, it's a great site already!
