### ISSUE TITLE
”Async is not defined” when try to add a project

### ISSUE THREAD

**Issue by sapegin** [michaelrambeau/bestofjs-webui#28]
1. Sign in.
2. Go to My Requests page.
3. Click “Add a project” button.

I see this error:

```
Uncaught ReferenceError: Async is not defined
```

![image 2016-10-04 at 9 59 10 am](https://cloud.githubusercontent.com/assets/70067/19066362/389f246e-8a19-11e6-9e32-039777a6a2e2.png)

Chrome 53 on a Mac.

**Comment by michaelrambeau** [comment]
Hello @sapegin !
I am sorry for the bug, I have just fixed it, could you please try again ?
Thank you for using bestof.js.org, let me know if you have any feedback to improve the application.

**Comment by sapegin** [comment]
Thanks! Works now ;-)

**Comment by michaelrambeau** [comment]
Thank you @sapegin , I got your request about "React Styleguidist" project.
It will be online in 48 hours (because the application needs at least 2 daily snapshots of Github daily stars to display trends), be patient!

**Comment by sapegin** [comment]
Coooool, thanks! 8-)
