### ISSUE TITLE
Performance issue in Firefox

### ISSUE THREAD

**Issue by michaelrambeau** [michaelrambeau/bestofjs-webui#3]
In Firefox, on my 5-year old Windows7 laptop, navigation is not smooth, every click on tag menu items takes a few seconds... that is really slow!
I did some tests using very small data (only 10 projects and 3 tags instead of 350 projects and 50 tags, for example) but it makes almost no difference.
It does not not look like the problem comes from processing data.
I checked [an older version](http://v10.development.bestofjs.divshot.io) of the application (before the react-router upgrade) but it is slow too, in Firefox
It seems to be related to react-router; maybe it has to do with binding DOM and click events but I have no clue...

**Comment by michaelrambeau** [comment]
I checked from the office and there was no problem with Firefox on Windows 7 (v41.0.1) and on Mac (v41.0.2).

**Comment by michaelrambeau** [comment]
Readings about performance:

https://ouicar.github.io/2016/02/05/bench-react.html

https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.4gunttn7q

**Comment by michaelrambeau** [comment]
6 months laters, it is still slow on Firefox!

Here is a screenshot taken from Firefox devtools performance tab.

![image](https://cloud.githubusercontent.com/assets/5546996/14509980/1f5b4d9e-020a-11e6-8ded-6e520f5a23c4.png)

You can see that the application FPS rate falls to 0, (the app becomes un-responsive) during about 2 seconds, after every click on the menu items.
Timeline says it is "DOM event" stuff (in yellow)

I did some [some changes](https://github.com/michaelrambeau/bestofjs-webui/commit/9fcb9ed4fc9aa377ad0b3bd4d48628e96591b961) to avoid rendering twice the `<App>` container when navigation occurs.

If a given tag page contains only one project, it is faster, so the problem seems to be related to the amount of DOM elements displayed on the page.

**Comment by michaelrambeau** [comment]
Babel plugin to optimize production code:

https://github.com/thejameskyle/babel-react-optimize

**Comment by michaelrambeau** [comment]
Using `react-addons-perf` to track "wasted time"

![image](https://cloud.githubusercontent.com/assets/5546996/14633965/ed8840a6-065a-11e6-9e97-b7a558105dd4.png)

**Comment by michaelrambeau** [comment]
An other approach to make pages display very fast AFTER the first access: use memoization

A very basic example that stores `<ProjectCard>` inside a cache, using the project `name` as a key, ignoring other properties.

```jsx
const cache = {};

const OptimizedProjectCard = (props) => {
  const key = props.project.name;
  let cached = cache[key];
  if (!cached) {
    cache[key] = <ProjectCard {...props} />;
    cached = cache[key];
  } else {
    // console.info('Using the cache', key);
  }
  return cached;
};

const ProjectCard = (props) => {
...
}
```

**Comment by michaelrambeau** [comment]
Perfomance measurement with `react-addons-perf`: rendering a page with 35 projects, in chrome and in Firefox

DOM | Time in FF | Time in Chrome
--- | --- | ---
1064 elements | 665 ms | 936 ms
408 elements | 453 ms | 427 ms
58 elements | 120 ms | 89 ms

These numbers do NOT explain why the page is slow in Firefox.

Firefox devtools, for the same page, show clearly that the page is "frozen" during more than 4 seconds.

![image](https://cloud.githubusercontent.com/assets/5546996/14725047/a8c14d54-0854-11e6-8075-eab77a081c95.png)

**Comment by michaelrambeau** [comment]
#### Testing preact

Testing a fast alternative to React: preact
With preact-compat, you are supposed to use preact instead of React without changing a single line of code!

I got some issues:

```
cannot resolve module preact-compat/lib/ReactMount
```
 => I disabled React Hot Loader

```
Required prop `store` was not specified in `Provider
```
=> I changed the launch process

```
Required prop `createElement` was not specified in `<<anonymous>>`
```

 => I had to add a `createElement` propery to Router object

```
// default behavior
function createElement(Component, props) {
  // make sure you pass all the props in!
  return <Component {...props}/>
}
...
      <Router history={ appHistory } createElement={createElement}>
         { getRoutes(10) }
      </Router>
```

And the last one, I am unable to solve right now:

```
Could not find "store" in either the context or props
```

????

**Comment by developit** [comment]
@michaelrambeau Feel free to drop into https://gitter.im/developit/preact - working on the router issue now.

**Comment by michaelrambeau** [comment]
@developit Nice, I will check the chat rooms on Gitter.

Thank you for that great project and for listening to all of us!

**Comment by michaelrambeau** [comment]
New tools to check performance:
* https://github.com/garbles/why-did-you-update
* https://github.com/RamonGebben/react-perf-tool
