### ISSUE TITLE
Search npms.io changed

### ISSUE THREAD

**Issue by Geczy** [michaelrambeau/bestofjs-webui#37]
Currently using

`https://npms.io/search?term=vue`

But it changed to

`https://npms.io/search?q=vue`

https://github.com/michaelrambeau/bestofjs-webui/blob/fa6bc9794af0a3bf7d6a88f38be3c6d1d8190b21/src/components/projects/NpmSection.jsx#L42

**Comment by michaelrambeau** [comment]
Hello @Geczy , thank you very much, that's a good catch.
I'm going to fix the npms.io search URL right now.
