### ISSUE TITLE
Should be able to add multiple tags to project

### ISSUE THREAD

**Issue by ragamufin** [michaelrambeau/bestofjs-webui#4]
Should be able to add several tags to a project and be able to search by them as well.

**Comment by michaelrambeau** [comment]
Projects can already have several tags (even if usually one one tag is assigned).
But from the left sidebar, you can only select one tag, so you cannot filter projects using several tags, that is true.

We could add a kind of search module, with a "autocomplete" field to add / remove tags.

Now the search engine (in the top bar) is quite basic: it filters projects using repository, title and description fields, from what the user entered, using RegExp.

Maybe a new "advanced search" page could be nice, with at least 2 fields:
* a text field with autocomplete feature to add / remove tags
* a text field to enter any keyword that appears in the project title, description or repository name (equivalent to the current search feature).

What do you think @ragamufin, do you have other ideas in mind about the UI ?

**Comment by ragamufin** [comment]
I was thinking the search box could be something like what is shown on the "Multiple Search Selection" of http://semantic-ui.com/modules/dropdown.html#search-selection

**Comment by michaelrambeau** [comment]
The example from semantic-ui is basically a "select multiple" component enhanced with an "autocomplete" feature.
So yes it could be used to filter by one or several tags, that is a nice UI.
But what to do with the search by keywords (the current search feature in the top bar) ?
Do we need 2 text fields ? Or can the 2 features be merged in one UI component ?

**Comment by ragamufin** [comment]
I have seen uis that allow you to do both, search by tag and free text. So as you're typing a dropdown shows up with tag recommendations and you can click on them and the tag goes into the search box, however if you don't click it then the text remains free text. Clicking multiple tags and having the free text results in the tags being listed first with a different style and the free text after. I guess semantic doesn't have a ui for that, I haven't checked. I can't think of where I've seen it but I know I have seen it on more than one occasion. If it's not out there it would actually be a useful discrete component to build.

Or, you could build a search interface with two fields, one like the link above for adding tags to the search and one with text. Then on submit check with both.

**Comment by michaelrambeau** [comment]
it is now possible to search projects by entering tag names in the search box (like "test", "static", "svg"...), since the release [0.3.2](https://github.com/michaelrambeau/bestofjs-webui/releases/tag/0.3.2)

**Comment by michaelrambeau** [comment]
Closing for now, as search algorithm improved as mentioned in the previous comment.

Current search is far from being perfect, an "auto-complete" component could be nice, or something more sophisticated like the search feature from Algolia, as can see on [React documentation site](http://facebook.github.io/react/) or on [ES Lint site](http://eslint.org/).

![image](https://cloud.githubusercontent.com/assets/5546996/15410919/74945026-1e57-11e6-8bce-34717b9abade.png)

![image](https://cloud.githubusercontent.com/assets/5546996/15410934/8cecf3c6-1e57-11e6-8fba-6939bfe1bb67.png)
