### ISSUE TITLE
Reduce the permissions that bestof.js can access

### ISSUE THREAD

**Issue by sradevski** [michaelrambeau/bestofjs-webui#42]
When I was logging in with my github account, it asked for **both read/write** access to both my public and private repositories. I am sure there are tons of people who would not feel comfortable with giving write permissions to someone, and it is not really necessary I think.

My suggestion is to ask only for **read** access, as that is more than enough to do any of the current and future functionalities of bestofjs.

**Comment by michaelrambeau** [comment]
Good catch Steve!

Of course we don't need **write** access at all, I was not careful when I did the setup.

I will fix that as soon as possible.

**Comment by michaelrambeau** [comment]
Hello again Steve @sradevski , I have just changed the permission, using the strict minimum:

```
Limited access to your public data
```

![image](https://user-images.githubusercontent.com/5546996/27540420-19ccc4c4-5abb-11e7-88a9-8a77c66bb95b.png)

Could you confirm that it's OK? Thank you in advance!

**Comment by sradevski** [comment]
I just confirmed it is just the public information. I think this can be closed.
