### ISSUE TITLE
Serve site over HTTPS

### ISSUE THREAD

**Issue by coliff** [michaelrambeau/bestofjs-webui#45]
It'd be nice to have the site served over HTTPS. There are many advantages such as: 

- Google rank HTTPS sites slightly higher as they are more trustworthy (http://googlewebmastercentral.blogspot.com/2014/08/https-as-ranking-signal.html)
- Some third-party HTTPS sites do not allow referring links to non-HTTPS sites to be tracked in Google Analytics. Using HTTPS can give more accurate analytics data.
- ISPs like Verizon and Comcast are now routinely injecting tracking material into their customers traffic -- using HTTPS protects visitors from being manipulated in this way. Also some airport and hotel wi-fi services add tracking and even adverts in to websites – but it’s impossible to do that with sites served over HTTPS
- Sites served over HTTPS look safer and more professional with the nice green padlock icon in the top URL bar.
- A growing number of web technologies and APIs require HTTPS
- Web browsers (Chrome and Firefox) are beginning to show non-HTTPS sites as non-secure. so they will appear less trustworthy.

If your site is hosted by GitHub you can get free SSL by using Cloudflare (I've done this before and it works great).

**Comment by michaelrambeau** [comment]
@coliff OK Christian, your arguments convinced me ;)

I have just made the request: https://github.com/js-org/dns.js.org/pull/1344

I will let you know when it's online, thank you!

**Comment by michaelrambeau** [comment]
@coliff It's done, we are on `https` my friend => https://bestof.js.org/

**Comment by michaelrambeau** [comment]
## `Mixed content` warning

I noticed a warning in Chrome DevTools:

> Mixed Content: The page at 'https://bestof.js.org/' was loaded over HTTPS, but requested an insecure image 'http://cdn.instantlogosearch.com/svg/svgporn/awesome.svg'. This content should also be served over HTTPS.

The reason: the page, served over HTTPS, includes some `HTTP` resources.
For some popular projects (including React, Redux, Awesome, Flow...) we display a SVG icon instead of the usual GitHub repo owner avatar.

We could host by ourselves these SVG icons (download them and somehow create a build process).

But the simplest solution would be to find a place where those popular SVG icons are served over `HTTPS`.

@coliff Let me know if you have any suggestion.

**Comment by michaelrambeau** [comment]
@coliff Ignore my previous request, I'm going to use SVG icon urls from this site: https://svgporn.com/ (SVG icons are served over `HTTPS`, yeah!).

So the problem of `Mixed Content` will be solved tomorrow in the morning, next time the site is rebuilt.

**Comment by coliff** [comment]
Great - let me know when the next site build goes live and I'll check it out.

**Comment by michaelrambeau** [comment]
@coliff It should be OK now, the application is served over `HTTPS` without any warning about `Mixed Content`.

**Comment by michaelrambeau** [comment]
## Screenshot

To be used in the README.md

![image](https://user-images.githubusercontent.com/5546996/27979469-459bc2cc-63b1-11e7-9a49-764841fc7fde.png)
