### ISSUE TITLE
Update Ember Link

### ISSUE THREAD

**Issue by danilovaz** [michaelrambeau/bestofjs-webui#49]
Hi @michaelrambeau ! 

Wonderful project :tada: 

I noticed that the link to Ember in NPM is not the correct one, I would like to correct but I did not find where I can make a PR or if it is just open an issue here. The correct NPM link for Ember is this one: https://www.npmjs.com/package/ember-source

Can you help me?

Thank you.

**Comment by michaelrambeau** [comment]
Hello Danilo @danilovaz ,
Thank you for your kinds words.

About Ember, good catch.
Actually the project list is maintained in a separate database, so creating an issue is the right thing to do, thank you!

bestof.js.org has just been rebuilt, could you check if it's OK now https://bestof.js.org/projects/ember ?

![image](https://user-images.githubusercontent.com/5546996/28988510-184b6498-79ab-11e7-91e1-4412d0c13962.png)


You're involved in the JavaScript community, so any feedback from you is more than welcome!
(Just in case you want to talk, there is a Slack channel, let me know if you want to join it)
