### ISSUE TITLE
Presentation for Rakuten Tech Conference 2017

### ISSUE THREAD

**Issue by michaelrambeau** [michaelrambeau/bestofjs-webui#55]
This issue is used to track ideas and store screenshots related to the presentation I will make at Rakuten Tech Conference 2017 (https://tech.rakuten.co.jp/).

### The problem with Javascript

* JavaScript is moving fast!
  * jQuery
  * Backbone
  * AngularJS
  * React
  * Vue
  * Next?
* How to track/remember the most interesting libraries?
* How to know if a project is still relevant?

### The solution

* https://bestof.js.org/ is a web application with 2 goals:
  * show the trends about web development, based on GitHub stars
  * help developers find the best libraries and components (fast search engine)

### Technology

* SPA made with React and Redux
* Serverless architecture (node.js micro-services)

### Some numbers

* +1000 projects
* +120 tags

### The community

* Open source project on GitHub
* Anyone can suggest new projects to add

**Comment by michaelrambeau** [comment]
## Screenshots

### Most popular frameworks

![image](https://user-images.githubusercontent.com/5546996/31548336-707c1b76-b065-11e7-8c93-2371c8a05072.png)

### Trending Today

![image](https://user-images.githubusercontent.com/5546996/31548386-94e32612-b065-11e7-885b-505a1f1bf7b4.png)

**Comment by sradevski** [comment]
Looking forward to the presentation! :)

**Comment by michaelrambeau** [comment]
The slides are online: http://rakuten2017.surge.sh

**Comment by michaelrambeau** [comment]
## Charts from Google Analytics

### By country

![image](https://user-images.githubusercontent.com/5546996/31944962-c29199da-b908-11e7-8e99-e276a988017e.png)

### Mobile VS Desktop

![image](https://user-images.githubusercontent.com/5546996/31945012-e7ee3468-b908-11e7-8e57-268335517660.png)

**Comment by michaelrambeau** [comment]
Done! https://twitter.com/michaelrambeau/status/924242867337412608
